### ISSUE TITLE
Uncaught TypeError: Promise.defer is not a function

### ISSUE THREAD

**Issue by NuclearCookie** [benjaminRomano/todo-manager#10]
[Enter steps to reproduce below:]

Not clear how. I just closed a tab and it popped up

**Atom Version**: 1.1.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [todo-manager](https://github.com/benjaminRomano/todo-manager) package, v0.2.6
### Stack Trace

Uncaught TypeError: Promise.defer is not a function

```
At /C:/Users/Pieter/.atom/packages/todo-manager/lib/regexMatcherUtil.coffee:103

TypeError: Promise.defer is not a function
    at RegexMatcherUtil.fetchFromWorkspace (C:\Users\Pieter\.atom\packages\todo-manager\lib\regexMatcherUtil.coffee:72:24)
    at RegexMatcherUtil.getMatches (C:\Users\Pieter\.atom\packages\todo-manager\lib\regexMatcherUtil.coffee:39:30)
    at TodoManager.getMatches (C:\Users\Pieter\.atom\packages\todo-manager\lib\views\todo-manager.coffee:108:23)
    at TodoManager.getMatchesForOpenFiles (C:\Users\Pieter\.atom\packages\todo-manager\lib\views\todo-manager.coffee:75:6)
    at TodoManager.getMatchesForOpenFiles (C:\Users\Pieter\.atom\packages\todo-manager\lib\views\todo-manager.coffee:1:1)
    at TodoManager.onPaneChanges (C:\Users\Pieter\.atom\packages\todo-manager\lib\views\todo-manager.coffee:65:8)
    at C:\Users\Pieter\.atom\packages\todo-manager\lib\views\todo-manager.coffee:1:1
    at Emitter.module.exports.Emitter.emit (C:\Users\Pieter\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at PaneContainer.module.exports.PaneContainer.didDestroyPaneItem (C:\Users\Pieter\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:289:27)
    at Pane.module.exports.Pane.removeItem (C:\Users\Pieter\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:398:17)
```
### Commands

```
     -9:54.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -9:54.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -9:53.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -9:50.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:49.2.0 core:save (atom-text-editor.editor.is-focused)
     -9:45.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -9:45.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -9:45.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -8:39.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -8:38 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -8:36.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:35.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -8:35.1.0 core:delete (atom-text-editor.editor.is-focused)
     -8:33.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -4:27.2.0 remote-sync:upload-file (span.name.icon.icon-file-zip)
     -4:13.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "todo-manager": {}
}
```
### Installed Packages

``` coffee
# User
atom-image-resize, v0.3.0
bottom-dock, v0.3.5
file-icons, v1.6.11
language-lua, v0.9.4
minimap, v4.16.0
project-manager, v2.6.5
remote-sync, v3.3.0
run-in-browser, v0.1.3
space-tab, v0.4.2
Sublime-Style-Column-Selection, v1.3.0
switch-header-source, v0.20.0
todo-manager, v0.2.6
w3c-validation, v0.2.0
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by benjaminRomano** [comment]
That's weird Promise.defer is definitely a function... If you open up the console (ctrl+alt+i) and type Promise.defer, does it throw an error?

**Comment by NuclearCookie** [comment]
Hey, Indeed, `Promise.defer` works if I insert it in the console. 
I've uninstalled this package because the crash was constant. If I have some time I'll try to reproduce and provide you with some more information

**Comment by benjaminRomano** [comment]
I'm closing this for now. Just create a new issue if you do find a way to reproduce it consistently.

**Comment by ramtinsoltani** [comment]
I just installed Atom 1.9.0 Beta 0 and upon opening the editor I get this error. `Promise.defer` returns `undefined` in the console.

**Comment by benjaminRomano** [comment]
Does this break anything for you or just shows an error message in the console?

**Comment by ramtinsoltani** [comment]
Can't use Atom with the package enabled (Atom keeps crashing). I had to disable the package and rerun Atom.

**Comment by benjaminRomano** [comment]
Lets see if we can figure out what's causing this. :smile: 

Did you experience this behavior in previous versions? What other packages do you have installed? Have you tried re-installing bottom-dock and todo-manager?

**Comment by twainj** [comment]
I am receiving the same error. It occurs every time I change tabs. No crashes yet, but the Todo-manager pane doesn't show any results. I tried uninstalling and re-installing to no avail.
I tried disabling it for now, but I was still receiving the error, until I closed and re-opened atom. 

Let me know if there is any other information I can provide, I can re-install and check it out.

Atom 1.9.0
Amazon Workspace (Windows Server 2008 R2)

<pre>
PS D:\Users\twainjMA1> apm list --installed --packages   
Community Packages (10) D:\Users\twainjMA1\.atom\packages
├── autoclose-html@0.23.0                                
├── bottom-dock@0.4.4                                    
├── editorconfig@1.4.1                                   
├── enhanced-tabs@1.7.0                                  
├── highlight-selected@0.11.2                            
├── language-asp@1.0.0                                   
├── simple-drag-drop-text@0.3.1                          
├── Sublime-Style-Column-Selection@1.6.0                 
├── symbols-tree-view@0.13.2                             
└── todo-manager@0.2.9                                   
                                                         
└── (empty)       
</pre>

**Comment by juliuszfedyk** [comment]
Same thing here, needed to remove the package

Community Packages (17)
├── atom-beautify@0.29.10
├── atom-terminal@0.8.0
├── bottom-dock@0.4.4
├── close-tags@0.6.0
├── color-picker@2.2.2
├── compare-files@0.6.2
├── copy-as-rtf@0.9.3
├── docblockr@0.7.4
├── emmet@2.4.3
├── line-count@0.5.0
├── linter@1.11.14
├── linter-js-standard@3.4.1
├── linter-jscs@4.0.5
├── linter-manager@0.2.12
├── project-manager@2.9.7
├── scope-inspector@1.0.1
└── sync-settings@0.7.2

└── (empty)

**Comment by yraies** [comment]
reinstalling the dock and todo-manager hasn't helped

here the error report by atom
1. activate package
2. get errors on Tab change

**Atom Version**: 1.9.0
**System**: Unknown Windows Version
**Thrown From**: [todo-manager](https://github.com/benjaminRomano/todo-manager) package, v0.2.9

### Stack Trace

Uncaught TypeError: Promise.defer is not a function

```
At /[User Path]/h.atom/packages/todo-manager/lib/regexMatcherUtil.coffee:103

TypeError: Promise.defer is not a function
    at RegexMatcherUtil.fetchFromWorkspace (file:///[User Path]/.atom/packages/todo-manager/lib/regexMatcherUtil.coffee:72:24)
    at RegexMatcherUtil.getMatches (file:///[User Path]/.atom/packages/todo-manager/lib/regexMatcherUtil.coffee:39:30)
    at TodoManager.getMatches (file:///[User Path]/.atom/packages/todo-manager/lib/views/todo-manager.coffee:108:23)
    at TodoManager.getMatchesForOpenFiles (file:///[User Path]/.atom/packages/todo-manager/lib/views/todo-manager.coffee:75:6)
    at TodoManager.getMatchesForOpenFiles (file:///[User Path]/.atom/packages/todo-manager/lib/views/todo-manager.coffee:1:1)
    at file:///[User Path]/.atom/packages/todo-manager/lib/views/todo-manager.coffee:53:8
    at Function.module.exports.Emitter.simpleDispatch ([User Path]\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit ([User Path]\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TableView.attached (file:///[User Path]/.atom/packages/todo-manager/node_modules/atom-bottom-dock/lib/table-view.coffee:74:14)
    at space-pen-div.View.element.attached ([User Path]\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:164:63)
    at space-pen-div.CustomElementPrototype.attachedCallback ([User Path]\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:51:55)
    at space-pen-div.<anonymous> ([User Path]\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\jquery\dist\jquery.js:5221:12)
    at DockPaneManager.jQuery.fn.extend.domManip ([User Path]\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\jquery\dist\jquery.js:5414:15)
    at DockPaneManager.jQuery.fn.extend.append ([User Path]\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\jquery\dist\jquery.js:5218:15)
    at DockPaneManager.addPane (file:///[User Path]/.atom/packages/bottom-dock/lib/views/dock-pane-manager.coffee:19:6)
    at BottomDock.addPane (file:///[User Path]/.atom/packages/bottom-dock/lib/views/bottom-dock.coffee:40:22)
    at BottomDockService.addPane (file:///[User Path]/.atom/packages/bottom-dock/lib/bottom-dock-service.coffee:20:17)
    at Object.module.exports.add (file:///[User Path]/.atom/packages/todo-manager/lib/main.coffee:62:17)
    at Object.module.exports.consumeBottomDock (file:///[User Path]/.atom/packages/todo-manager/lib/main.coffee:74:6)
    at Provider.module.exports.Provider.provide ([User Path]\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at [User Path]\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:30.2.0 grammar-selector:show (atom-text-editor.editor)
     -0:28 line-ending-selector:show (atom-text-editor.editor.is-focused)
  4x -0:24 git-status:toggle (atom-text-editor.editor.is-focused)
     -0:20.4.0 window:run-package-specs (atom-text-editor.editor.is-focused)
     -0:16.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -0:13.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:09.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.2.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "project-manager"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10 (inactive)
atom-fix-path, v0.1.0 (active)
bottom-dock, v0.4.4 (active)
file-icons, v1.7.17 (active)
git-control, v0.8.2 (inactive)
git-status, v0.3.4 (active)
highlight-selected, v0.11.2 (active)
minimap, v4.24.7 (active)
minimap-cursorline, v0.2.0 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-pigments, v0.2.1 (active)
pigments, v0.31.2 (active)
project-manager, v2.9.7 (inactive)
todo-manager, v0.2.9 (inactive)
tool-bar, v1.0.0 (active)
tool-bar-atom, v1.6.3 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by benjaminRomano** [comment]
I'll look into this in the next couple of days.

**Comment by naren-m** [comment]
I am seeing this error, every time i try to open atom.

**Comment by benjaminRomano** [comment]
Should be fixed now. Sorry about the inconvenience

**Comment by twainj** [comment]
Awesome, thanks Benjamin! I just installed 2.10, and everything is working beautifully.
Thanks for a great plugin!
